nginx:
  image: nginx
  volumes:
    - /opt/gopath/src/github.com/ChainNova/poc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /opt/gopath/src/github.com/ChainNova/poc/nginx/conf/app_adaptor.conf:/etc/nginx/conf.d/app_adaptor.conf
  ports:
    - 8080:80
  environment:
    -  NGINX_PORT=80
    
app:
  image: chainnova/exchange-app
  command: app
  environment:
    - APP_REDIS_ADDRESS=120.92.77.55:6379
    - APP_APP_ADAPTOR_ADDRESS=http://120.92.77.55:8080
  #  - APP_CHAINCODE_BUSINESS_PATH=github.com/ChainNova/poc/chaincode/exchange-chaincode
    - APP_CHAINCODE_BUSINESS_PATH=github.com/ChainNova/poc/chaincode/chaincode_example02
  #links:
   # - nginx
    #- adaptor
  ports:
    - 7060:7060