nginx0:
  image: nginx
  volumes:
    - /opt/gopath/src/github.com/Chainnova/poc/conf/nginx.conf:/etc/nginx/nginx.conf
    - /opt/gopath/src/github.com/Chainnova/poc/conf/app_adaptor.conf:/etc/nginx/conf.d/app_adaptor.conf
  ports:
    - 8081:80
  environment:
    -  NGINX_PORT=80