nginx-ad:
  image: nginx
  volumes:
    - /opt/gopath/src/github.com/ChainNova/poc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /opt/gopath/src/github.com/ChainNova/poc/nginx/conf/app_adaptor.conf:/etc/nginx/conf.d/app_adaptor.conf
  ports:
    - 8080:80
    - 8081:81
  environment:
    -  NGINX_PORT=80